kind: pipeline
name: build-test-publish-develop-docker-image
type: docker

steps:
  - name: build #build the frontend docker image
    image: docker:latest
    commands:
      - docker build --no-cache --build-arg branch=${DRONE_BRANCH} -t drone-tezedge-explorer:latest -f Dockerfile .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

  - name: frontend-server
    image: drone-tezedge-explorer:latest
    pull: if-not-exists
    detach: true
    privileged: true
    environment:
      API: '[{"id":"drone","name":"drone-test-node","http":"http://develop.dev.tezedge.com:18732","p2p_port":"9732","features": [{ "name": "ws", "url": "ws://develop.dev.tezedge.com:4927" },{ "name": "debugger", "url": "http://develop.dev.tezedge.com:17732" },{ "name": "sandbox", "url": "http://develop.dev.tezedge.com:3030" },{ "name": "commit", "id": "develop" },{ "name": "monitoring" },{ "name": "resources/system", "monitoringUrl": "http://develop.dev.tezedge.com:38732/resources/tezedge" },{ "name": "resources/memory", "memoryProfilerUrl": "http://develop.dev.tezedge.com:17832" },{ "name": "resources/storage" },{ "name": "mempool" },{ "name": "storage" },{ "name": "network" },{ "name": "logs" }]}]'

  - name: test-app
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/app/app.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-logs
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/logs/logs.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-commit-number
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/monitoring/commit-number/commit-number.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-network
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/network/network-action/network.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-open-api
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/open-api/open-api.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-system-resources
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/resources/system-resources.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-storage-resources
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/resources/storage-resources.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-memory-resources
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/resources/memory-resources.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-routing
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/routing/routing.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-sandbox
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/sandbox/sandbox.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-settings-node
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/settings-node/settings-node.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-progress-bar
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/shared/progress-bar.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-storage-action
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/storage/storage-action/storage-action.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-storage-block
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/storage/storage-block/storage-block.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: publish
    image: plugins/docker
    settings:
      repo: tezedge/tezedge-explorer
      tags: latest
      dockerfile: Dockerfile
      build_args:
        - branch=develop
        - commit=${DRONE_COMMIT}
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

image_pull_secrets:
  - docker_pull_secret

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - develop
  event: push

---
# when pushing on master these pipelines are executed

kind: pipeline
name: build-test-publish-lastest-tagged-docker-image
type: docker

steps:
  - name: build #build the frontend docker image
    image: docker:latest
    commands:
      - docker build --no-cache --build-arg branch=master -t drone-tezedge-explorer:latest -f Dockerfile .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

  - name: frontend-server #detach it to access it inside test step
    image: drone-tezedge-explorer:latest
    pull: if-not-exists
    detach: true
    privileged: true
    environment:
      API: '[{"id":"drone","name":"drone-test-node","http":"http://develop.dev.tezedge.com:18732","p2p_port":"9732","features": [{ "name": "ws", "url": "ws://develop.dev.tezedge.com:4927" },{ "name": "debugger", "url": "http://develop.dev.tezedge.com:17732" },{ "name": "sandbox", "url": "http://develop.dev.tezedge.com:3030" },{ "name": "commit", "id": "develop" },{ "name": "monitoring" },{ "name": "resources/system", "monitoringUrl": "http://develop.dev.tezedge.com:38732/resources/tezedge" },{ "name": "resources/memory", "memoryProfilerUrl": "http://develop.dev.tezedge.com:17832" },{ "name": "resources/storage" },{ "name": "mempool" },{ "name": "storage" },{ "name": "network" },{ "name": "logs" }]}]'

  - name: test-app
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/app/app.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-logs
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/logs/logs.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-commit-number
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/monitoring/commit-number/commit-number.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-network
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/network/network-action/network.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-open-api
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/open-api/open-api.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-system-resources
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/resources/system-resources.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-storage-resources
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/resources/storage-resources.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-memory-resources
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/resources/memory-resources.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-routing
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/routing/routing.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-sandbox
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/sandbox/sandbox.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-settings-node
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/settings-node/settings-node.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-progress-bar
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/shared/progress-bar.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-storage-action
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/storage/storage-action/storage-action.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: test-storage-block
    image: cypress/included:6.2.1
    commands:
      - cypress run --spec "cypress/integration/storage/storage-block/storage-block.spec.js"
    environment:
      CYPRESS_baseUrl: http://frontend-server:80

  - name: publish
    image: plugins/docker
    settings:
      repo: tezedge/tezedge-explorer
      tags:
        - ${DRONE_TAG}
        - latest-release
      dockerfile: Dockerfile
      build_args:
        - branch=master
        - commit=${DRONE_COMMIT}
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

  - name: cp-static
    image: drone-tezedge-explorer:latest
    privileged: true
    pull: if-not-exists
    volumes:
      - name: static_page
        path: /etc/static_page
    commands:
      - rm -rf /etc/static_page/*
      - cp -R /usr/share/nginx/html/* /etc/static_page

  - name: publish-firebase
    image: devillex/docker-firebase
    pull: if-not-exists
    volumes:
      - name: static_page
        path: /drone/src/dist/tezedge-explorer
    environment:
      FIREBASE_API_TOKEN:
        from_secret: FIREBASE_API_TOKEN
    commands:
      - firebase deploy --token=$${FIREBASE_API_TOKEN}

image_pull_secrets:
  - docker_pull_secret

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: static_page
    host:
      path: /etc/tezedge-ci/tezedge-explorer/

trigger:
  ref: refs/tags/**
