version: '3'
services:
  tezedge-explorer:
    image: tezedge/tezedge-explorer:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - API=[{"id":"rust","type":"tezedge","name":"rust.master.dev.tezedge","http":"http://master.dev.tezedge.com:18732","p2p_port":"9732","features":[{"name":"ws","url":"ws://develop.dev.tezedge.com:4927"}, {"name":"debugger", "url":"http://develop.dev.tezedge.com:17732" },{ "name":"sandbox", "url":"http://localhost:3030" },{ "name":"commit", "id":"develop" },{ "name":"monitoring" },{ "name":"resources/system", "monitoringUrl":"http://develop.dev.tezedge.com:38732/resources/tezedge" },{ "name":"resources/memory", "memoryProfilerUrl":"http://develop.dev.tezedge.com:17832" },{ "name":"resources/storage" },{ "name":"mempool" },{ "name":"storage" },{ "name":"network" },{ "name":"logs"}]}]
    hostname: tezedge-explorer
    # network_mode: host
  cypress:
    image: "cypress/included:6.2.1"
    depends_on:
      - tezedge-explorer
    environment:
      - CYPRESS_baseUrl=http://docker.for.mac.localhost:8080
    working_dir: /e2e
    volumes:
    - ./:/e2e
